countries_name = {
    "CN": "China",
    "IN": "India",
    "US": "United States",
    "ID": "Indonesia",
    "PK": "Pakistan",
    "BR": "Brazil",
    "NG": "Nigeria",
    "BD": "Bangladesh",
    "RU": "Russia",
    "MX": "Mexico",
    "JP": "Japan",
    "ET": "Ethiopia",
    "PH": "Philippines",
    "EG": "Egypt",
    "VN": "Vietnam",
    "CD": "Democratic Republic of the Congo",
    "IR": "Iran",
    "TR": "Turkey",
    "DE": "Germany",
    "TH": "Thailand",
    "GB": "United Kingdom",
    "FR": "France",
    "IT": "Italy",
    "TZ": "Tanzania",
    "ZA": "South Africa",
    "MM": "Myanmar (Burma)",
    "KE": "Kenya",
    "KR": "South Korea",
    "CO": "Colombia",
    "ES": "Spain",
    "UG": "Uganda",
    "AR": "Argentina",
    "UA": "Ukraine",
    "DZ": "Algeria",
    "SD": "Sudan",
    "IQ": "Iraq",
    "AF": "Afghanistan",
    "PL": "Poland",
    "CA": "Canada",
    "MA": "Morocco",
    "SA": "Saudi Arabia",
    "PE": "Peru",
    "AO": "Angola",
    "MY": "Malaysia",
    "MO": "Mozambique",
    "GH": "Ghana",
    "YE": "Yemen",
    "NP": "Nepal",
    "CM": "Cameroon",
    "CI": "Ivory Coast",
    "BF": "Burkina Faso",
    "AU": "Australia",
    "NE": "Niger",
    "KP": "North Korea",
    "MW": "Malawi",
    "LK": "Sri Lanka",
    "KZ": "Kazakhstan",
    "KG": "Kyrgyzstan",
    "TJ": "Tajikistan",
    "TM": "Turkmenistan",
    "UZ": "Uzbekistan"
}
